### ISSUE TITLE
请问实时通信如何集成自身用户体系

### ISSUE THREAD

**Issue by quansenx** [leancloud/leanmessage-javascript-sdk#12]
RT

**Comment by wangxiao** [comment]
peerId 为自定义的用户体系名称。
另外，可以试用最新的 2.0 版本。
http://github.com/leancloud/js-realtime-sdk

**Comment by quansenx** [comment]
@wangxiao 我现在实现方式是通过收到消息时触发 message 方法，然后拿 fromPeerId 到自己的用户体系中去拉取该用户信息进行集成的。不知道除了该方式外还有没有其他更好的方法。谢谢！

**Comment by wangxiao** [comment]
确实是这样用的，实时通信和聊天关系是解耦的。

**Comment by quansenx** [comment]
@wangxiao 请问有没有消息读取的触发方法，比如同一个用户在web端跟移动端同时收到一条消息会在列表显示①这样的提醒，然后在移动端查看了该消息，请问我要如何在web监听到该消息已经被查看过了，谢谢！

**Comment by quansenx** [comment]
@wangxiao 如果没有消息读取回执事件的话，我想在查看新消息的时候再给对方发送一条特殊含义的信息进行多终端UI视图展示的同步。酱紫感觉有点狗血~囧~

**Comment by wangxiao** [comment]
2.0 beta 版本已经发布，支持回执的。
https://leancloud.cn/docs/js_realtime.html
